name: "publish"
on:
  workflow_dispatch:
  release:
    types: [published]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 6.0.2
      - name: submodule
        run: git submodule update --init --recursive
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Zip Extension
        run: pnpm run pack:zip
      - name: Browser Plugin Publish
        uses: PlasmoHQ/bpp@v2
        with:
          artifact: "extension.zip"
          keys: ${{ secrets.BPP_KEYS }}
